#%RAML 1.0 NamedExample

value:
  -
    OfferID: 24
    Status: Accepted
    DateCreated: 2022-07-12
    DateApproved: 2022-07-16
    EmployeeID: 6
    CustomerID: ALPHA
    ProductID: 69
    TotalPrice: 12.50
    PriceDiscount: 1.5
    PaymentTransactionID: 1a2b3c
    Quantity: 5
  -
    OfferID: 24
    Status: Accepted
    DateCreated: 2022-07-12
    DateApproved: 2022-07-16
    EmployeeID: 6
    CustomerID: ALPHA
    ProductID: 69
    TotalPrice: 12.50
    PriceDiscount: 1.5
    PaymentTransactionID: 1a2b3c
    Quantity: 5