http-listener:
  host: "localhost"
  port: "8084"
  
http-request:
  host: "localhost"
  port: "8085"
  

db:
  host: "localhost"
  port: "3306"
  user: "root"
  password: "$V,]ms^3hjqCxzq"
  database: "northwind"