#%RAML 1.0
title: Northwind-Customer-Exp-API


types:
  Customer: !include Datatypes/Customer.raml
  OfferRequest: !include Datatypes/OfferRequest.raml
  OfferDecision: !include Datatypes/OfferDecision.raml


/customers:
  get:
    description: "Retrieves customer data"
    responses:
      200:
        body:
          application/json:
            type: Customer[]
            examples:
              output: !include Examples/CustomersExample.raml
        
  post:
    description: "Registers a new customer in the Northwind Database"
    body:
      application/json:
        type: Customer
        examples:
          input: !include Examples/CustomerExample.raml
    responses:
      201:
        body:
          application/json:
            example:
              message: Customer added successfully
  /offerreq:
    post:
      body:
        application/json:
          type: OfferRequest
          examples:
            value: !include Examples/OfferRequestExample.raml
      responses:
        201:
          body:
            application/json:
              example:
                message: Offer requested, your OfferID is 12
  /offerdec:
    put:
      body:
        application/json:
          type: OfferDecision
          examples:
            value: !include Examples/OfferDecisionExample.raml
      responses:
        201:
          body:
            application/json:
              example:
                message: You have accepted the offer!
  /offers:
    get:
      queryParameters:
        CustomerID:
          required: true
      responses:
        200:
          body:
            application/json:
              example: !include Examples/OffersAcceptedExample.raml