http:
  port: "8081"

orderrequest: 
  host: "localhost"
  port: "8080"

offerrequest:
  host: "localhost"
  port: "8083"

shippingrequest:
  host: "localhost"
  port: "8084"

CustomerEXP:
  host: "localhost"
  port: "8085"

CustomerSYS:
  host: "localhost"
  port: "8086"